### PR TITLE
Add xdotool to default install

### PR DESCRIPTION
**Pull request by jpouellet**
Needed for better window killing: https://github.com/QubesOS/qubes-issues/issues/881#issuecomment-259903338

Addition approved by @marmarek in https://github.com/QubesOS/qubes-issues/issues/881#issuecomment-259927960

### CODE REVIEW

**Comment by jpouellet** [comment]
If we add it to the default `base-x` group like this, does it mean we can also [remove it from debug.ks](https://github.com/QubesOS/qubes-installer-qubes-os/blob/32531edb26856f103ae109c5c09313dd24cb9a92/conf/debug.ks#L15)?

**Comment by jpouellet** [comment]
Hmm... build failed, and I'm not sure why.

Only thing I can think of would be maybe I need to add some config someplace informing qubes-builder to download xdotool in get-sources phase? Or something?

Grepping through sources hasn't turned up anything obvious so far...

**Comment by marmarek** [comment]
This isn't the right place to add xdotool package. If a script need it, it should be added as particular package dependency.

As for build failure - it looks unrelated to your change.

**Comment by jpouellet** [comment]
Noted. Thanks.

**Pull request closed without merging**
