### PR TITLE
Anaconda patches

### PR DESCRIPTION
**Pull request by fepitre**
@marmarek : can you review all the extracted code/commits? I have not tested yet on an install but the diff between patched source and the qubes anaconda should be good. To do this, I cleared qubes anaconda sources by removing all files generated by autogen.sh (https://github.com/fepitre/qubes-installer-qubes-os/commit/0e31e4996e26f398a02b3a018bc0166ce0b3321a).

### CODE REVIEW

**Review by marmarek — CHANGES_REQUESTED** [review]
Those commits got lost: 
 - https://github.com/QubesOS/qubes-installer-qubes-os/commit/5796c78979af338b1173d4901a0069b84f5ecf49
 - https://github.com/QubesOS/qubes-installer-qubes-os/commit/23a54d74365dbef68ec4afbafc2bd850d8da26d0

Also, since 0014-... modifies configure.ac, `autoreconf` needs to be called before configure (similar thing was part of `autogen.sh`, but it's gone now).

**Comment by marmarek** [comment]
Also, anaconda-25.20.9.tar.bz2 differs from the one from upstream src.rpm or github. Please use one of them (I suggest the one from src.rpm, as the github one have weird directory prefix).

**Comment by marmarek** [comment]
One more thing: patches should preserve original Author: field.

**Comment by fepitre** [comment]
Yes. I rebuilt the source manually so I will extract the corresponding src.rpm version. The same for the fc29 branch for other components. For author in patches, I will edit manually all the extracted author in commits.

**Review by marmarek — APPROVED** [review]

**Comment by fepitre** [comment]
I forgot, just let me fix the patch list in the spec.

**Pull request merged**
